### ISSUE TITLE
运行不了啊,在win10 + Pycharm上

### ISSUE THREAD

**Issue by luohuatan** [13691579846/PytestAutoTestFrameWork#6]
(venv) C:\projects\PytestAutoTestFrameWork>python RunTestCase.py
Traceback (most recent call last):
  File "C:\projects\PytestAutoTestFrameWork\RunTestCase.py", line 11, in <module>
    import pytest
  File "C:\projects\PytestAutoTestFrameWork\venv\lib\site-packages\pytest.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "C:\projects\PytestAutoTestFrameWork\venv\lib\site-packages\_pytest\assertion\__init__.py", line 6, in <module>
    from _pytest.assertion import rewrite
  File "C:\projects\PytestAutoTestFrameWork\venv\lib\site-packages\_pytest\assertion\rewrite.py", line 20, in <module>
    from _pytest.assertion import util
  File "C:\projects\PytestAutoTestFrameWork\venv\lib\site-packages\_pytest\assertion\util.py", line 5, in <module>
    import _pytest._code
  File "C:\projects\PytestAutoTestFrameWork\venv\lib\site-packages\_pytest\_code\__init__.py", line 2, in <module>
    from .code import Code  # noqa
  File "C:\projects\PytestAutoTestFrameWork\venv\lib\site-packages\_pytest\_code\code.py", line 11, in <module>
    import pluggy
  File "C:\projects\PytestAutoTestFrameWork\venv\lib\site-packages\pluggy\__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "C:\projects\PytestAutoTestFrameWork\venv\lib\site-packages\pluggy\manager.py", line 6, in <module>
    import importlib_metadata
  File "C:\projects\PytestAutoTestFrameWork\venv\lib\site-packages\importlib_metadata\__init__.py", line 478, in <module>
    __version__ = version(__name__)
  File "C:\projects\PytestAutoTestFrameWork\venv\lib\site-packages\importlib_metadata\__init__.py", line 445, in version
    return distribution(package).version
  File "C:\projects\PytestAutoTestFrameWork\venv\lib\site-packages\importlib_metadata\__init__.py", line 418, in distribution
    return Distribution.from_name(package)
  File "C:\projects\PytestAutoTestFrameWork\venv\lib\site-packages\importlib_metadata\__init__.py", line 179, in from_name
    dists = resolver(name)
  File "<frozen importlib._bootstrap_external>", line 1454, in find_distributions
  File "C:\Users\94393\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 487, in find_distributions
    found = cls._search_paths(context.name, context.path)
AttributeError: 'str' object has no attribute 'name'

**Comment by Sun5211** [comment]
因为作者可能用的python2

**Comment by 13691579846** [comment]
用的python3  看起来是环境问题
